# Generated by Django 3.2.13 on 2022-06-19 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api_app', '0002_db_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='DB_project_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='-', max_length=50, null=True)),
                ('desc', models.CharField(blank=True, default='-', max_length=100, null=True)),
                ('creator', models.IntegerField(default=0)),
            ],
        ),
    ]
