# Generated by Django 3.2.13 on 2022-06-26 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api_app', '0003_db_project_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_project_list',
            name='mock',
            field=models.CharField(blank=True, default='mock_data', max_length=50, null=True),
        ),
    ]
