# Generated by Django 3.2.13 on 2022-06-26 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api_app', '0005_auto_20220626_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_project_list',
            name='priviate',
            field=models.BooleanField(default=True),
        ),
    ]
