# Generated by Django 3.2.13 on 2022-06-26 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api_app', '0006_alter_db_project_list_priviate'),
    ]

    operations = [
        migrations.CreateModel(
            name='DB_env_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(blank=True, default='http://', max_length=20, null=True)),
                ('type', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('des', models.CharField(blank=True, default='', max_length=20, null=True)),
            ],
        ),
    ]
