# Generated by Django 3.2.13 on 2022-07-09 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api_app', '0008_db_api_shop_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_news',
            name='date',
            field=models.CharField(default='_', max_length=50, null=True),
        ),
    ]
