# Generated by Django 3.2.13 on 2022-07-10 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api_app', '0011_db_power'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DB_power',
            new_name='DB_power_list',
        ),
    ]
