# Generated by Django 3.2.13 on 2022-07-10 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api_app', '0012_rename_db_power_db_power_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_power_list',
            name='path',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
