# Generated by Django 3.2.13 on 2022-09-05 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api_app', '0013_db_power_list_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='db_project_list',
            old_name='L_data',
            new_name='db',
        ),
        migrations.RenameField(
            model_name='db_project_list',
            old_name='P_data',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='db_project_list',
            name='mock',
        ),
        migrations.RemoveField(
            model_name='db_project_list',
            name='power',
        ),
        migrations.RemoveField(
            model_name='db_project_list',
            name='sign',
        ),
    ]
