# Generated by Django 3.2.13 on 2022-09-05 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api_app', '0014_auto_20220905_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='db_project_list',
            name='db',
        ),
        migrations.AddField(
            model_name='db_project_list',
            name='choose_api',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='db_project_list',
            name='doing_api',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='db_project_list',
            name='end_result',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='db_project_list',
            name='sql_host',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='db_project_list',
            name='sql_port',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='db_project_list',
            name='sql_pwd',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='db_project_list',
            name='sql_user',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='db_project_list',
            name='email',
            field=models.CharField(blank=True, default='[]', max_length=500, null=True),
        ),
    ]
