# Generated by Django 3.2.13 on 2022-09-09 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api_app', '0015_auto_20220905_1721'),
    ]

    operations = [
        migrations.CreateModel(
            name='DB_apis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField(default=0)),
                ('label', models.CharField(blank=True, default='新接口', max_length=100, null=True)),
                ('type', models.CharField(blank=True, default='api', max_length=10, null=True)),
                ('children', models.CharField(blank=True, default='[]', max_length=5000, null=True)),
            ],
        ),
    ]
