# Generated by Django 3.2.13 on 2022-09-18 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api_app', '0017_rename_choose_api_db_project_list_dck'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_apis',
            name='des',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='db_apis',
            name='headers',
            field=models.CharField(blank=True, default='[]', max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='db_apis',
            name='host',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='db_apis',
            name='method',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='db_apis',
            name='params',
            field=models.CharField(blank=True, default='[]', max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='db_apis',
            name='path',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='db_apis',
            name='payload_GQL_g',
            field=models.CharField(blank=True, default='', max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='db_apis',
            name='payload_GQL_q',
            field=models.CharField(blank=True, default='', max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='db_apis',
            name='payload_fd',
            field=models.CharField(blank=True, default='[]', max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='db_apis',
            name='payload_method',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='db_apis',
            name='payload_raw',
            field=models.CharField(blank=True, default='', max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='db_apis',
            name='payload_raw_method',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='db_apis',
            name='payload_xwfu',
            field=models.CharField(blank=True, default='[]', max_length=3000, null=True),
        ),
    ]
