# Generated by Django 3.2.13 on 2022-10-06 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api_app', '0018_auto_20220918_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_apis',
            name='payload_binary',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
