# Generated by Django 3.2.13 on 2022-10-09 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api_app', '0023_auto_20221009_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_api_shop_list',
            name='headers',
            field=models.CharField(blank=True, default='[]', max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='db_api_shop_list',
            name='params',
            field=models.CharField(blank=True, default='[]', max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='db_api_shop_list',
            name='payload_fd',
            field=models.CharField(blank=True, default='[]', max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='db_api_shop_list',
            name='payload_xwfu',
            field=models.CharField(blank=True, default='[]', max_length=3000, null=True),
        ),
    ]
