# Generated by Django 3.2.13 on 2022-10-23 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api_app', '0024_auto_20221009_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='DB_report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('ctime', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('all_result', models.BooleanField(default=True)),
                ('api_result', models.TextField(default='[]')),
            ],
        ),
    ]
