# Generated by Django 3.2.13 on 2022-12-18 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api_app', '0027_db_project_list_catch_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_news',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
